-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.curso
(
    id_curso serial NOT NULL,
    titulo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion date DEFAULT CURRENT_DATE,
    estado estado_curso NOT NULL DEFAULT 'activo'::estado_curso,
    imagen_url character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT curso_pkey PRIMARY KEY (id_curso)
);

CREATE TABLE IF NOT EXISTS public.intento_quiz
(
    id_intento serial NOT NULL,
    id_usuario integer NOT NULL,
    id_quiz integer NOT NULL,
    calificacion integer,
    tiempo_tomado integer,
    fecha_intento timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT intento_quiz_pkey PRIMARY KEY (id_intento)
);

CREATE TABLE IF NOT EXISTS public.logro
(
    id_logro serial NOT NULL,
    titulo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    condicion character varying(255) COLLATE pg_catalog."default",
    icono character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT logro_pkey PRIMARY KEY (id_logro)
);

CREATE TABLE IF NOT EXISTS public.modulo
(
    id_modulo serial NOT NULL,
    titulo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    orden integer NOT NULL,
    contenido_teorico text COLLATE pg_catalog."default",
    id_curso integer NOT NULL,
    estatus estatus_modulo NOT NULL DEFAULT 'activo'::estatus_modulo,
    CONSTRAINT modulo_pkey PRIMARY KEY (id_modulo)
);

CREATE TABLE IF NOT EXISTS public.pregunta
(
    id_pregunta serial NOT NULL,
    id_quiz integer NOT NULL,
    enunciado text COLLATE pg_catalog."default" NOT NULL,
    orden numeric NOT NULL,
    CONSTRAINT pregunta_pkey PRIMARY KEY (id_pregunta)
);

CREATE TABLE IF NOT EXISTS public.quiz
(
    id_quiz serial NOT NULL,
    id_modulo integer NOT NULL,
    titulo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    tiempo_limite_segundos integer,
    puntos_recompensa integer DEFAULT 0,
    CONSTRAINT quiz_pkey PRIMARY KEY (id_quiz)
);

CREATE TABLE IF NOT EXISTS public.rango
(
    id_rango serial NOT NULL,
    titulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    min_experiencia integer NOT NULL,
    icono character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT rango_pkey PRIMARY KEY (id_rango)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_rango_actual integer,
    experiencia_total integer DEFAULT 0,
    fecha_registro date DEFAULT CURRENT_DATE,
    rol rol_usuario DEFAULT 'student'::rol_usuario,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuario_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.usuario_logro
(
    id_relacion serial NOT NULL,
    id_usuario integer NOT NULL,
    id_logro integer NOT NULL,
    fecha_obtencion date DEFAULT CURRENT_DATE,
    CONSTRAINT usuario_logro_pkey PRIMARY KEY (id_relacion),
    CONSTRAINT unique_usuario_logro UNIQUE (id_usuario, id_logro)
);

CREATE TABLE IF NOT EXISTS public.opcion
(
    id_opcion serial,
    id_pregunta numeric,
    "Texto" text NOT NULL,
    es_correcta boolean NOT NULL DEFAULT false,
    orden numeric,
    PRIMARY KEY (id_opcion)
);

ALTER TABLE IF EXISTS public.intento_quiz
    ADD CONSTRAINT fk_intento_quiz FOREIGN KEY (id_quiz)
    REFERENCES public.quiz (id_quiz) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.intento_quiz
    ADD CONSTRAINT fk_intento_usuario FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.modulo
    ADD CONSTRAINT fk_modulo_curso FOREIGN KEY (id_curso)
    REFERENCES public.curso (id_curso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pregunta
    ADD CONSTRAINT fk_pregunta_quiz FOREIGN KEY (id_quiz)
    REFERENCES public.quiz (id_quiz) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.quiz
    ADD CONSTRAINT fk_quiz_modulo FOREIGN KEY (id_modulo)
    REFERENCES public.modulo (id_modulo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT fk_usuario_rango FOREIGN KEY (id_rango_actual)
    REFERENCES public.rango (id_rango) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.usuario_logro
    ADD CONSTRAINT fk_usuario_logro_logro FOREIGN KEY (id_logro)
    REFERENCES public.logro (id_logro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usuario_logro
    ADD CONSTRAINT fk_usuario_logro_usuario FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.opcion
    ADD CONSTRAINT fk_pregunta_opcion FOREIGN KEY (id_pregunta)
    REFERENCES public.pregunta (id_pregunta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;